// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0wIPjEqhXDKEhHbcDSDqim5J-PPapvA',
    appId: '1:587345643988:web:5288a175eb320710c16e41',
    messagingSenderId: '587345643988',
    projectId: 'fixit-2a354',
    authDomain: 'fixit-2a354.firebaseapp.com',
    storageBucket: 'fixit-2a354.firebasestorage.app',
    measurementId: 'G-SQ48YF6T7K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2RQ4BeAwKjKhX2HaV3_TpSXCKoQfaUc',
    appId: '1:587345643988:ios:51d5498f8756bad3c16e41',
    messagingSenderId: '587345643988',
    projectId: 'fixit-2a354',
    storageBucket: 'fixit-2a354.firebasestorage.app',
    androidClientId: '587345643988-fbu4v8gkqml3o4j9e49dgjv78nqdsu0t.apps.googleusercontent.com',
    iosClientId: '587345643988-17m89ogm1u2d6a9vrdhmido5et63k5pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS0wIPjEqhXDKEhHbcDSDqim5J-PPapvA',
    appId: '1:587345643988:web:5288a175eb320710c16e41',
    messagingSenderId: '587345643988',
    projectId: 'fixit-2a354',
    authDomain: 'fixit-2a354.firebaseapp.com',
    storageBucket: 'fixit-2a354.firebasestorage.app',
    measurementId: 'G-SQ48YF6T7K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2RQ4BeAwKjKhX2HaV3_TpSXCKoQfaUc',
    appId: '1:587345643988:ios:51d5498f8756bad3c16e41',
    messagingSenderId: '587345643988',
    projectId: 'fixit-2a354',
    storageBucket: 'fixit-2a354.firebasestorage.app',
    androidClientId: '587345643988-fbu4v8gkqml3o4j9e49dgjv78nqdsu0t.apps.googleusercontent.com',
    iosClientId: '587345643988-17m89ogm1u2d6a9vrdhmido5et63k5pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrt-47c1gz7e6l3CHyOkbeanq7dGR9w4',
    appId: '1:587345643988:android:d4c7b63c5a096eedc16e41',
    messagingSenderId: '587345643988',
    projectId: 'fixit-2a354',
    storageBucket: 'fixit-2a354.firebasestorage.app',
  );

}